# ======================================================================
# Clynz Team Pipeline
# ======================================================================

name: Deploy Clynz

on:
  pull_request:
    branches: [dev, staging, prod]
    paths:
      - 'Deployment/Spoke/Clynz/**'
      - 'Workload/Spoke/Clynz/**'
      - 'Modules/service-project/**'
      - 'Modules/compute-vm/**'
      - 'Modules/cloud-sql/**'
      - 'Modules/storage-bucket/**'
  push:
    branches: [dev, staging, prod]
    paths:
      - 'Deployment/Spoke/Clynz/**'
      - 'Workload/Spoke/Clynz/**'
      - 'Modules/service-project/**'
      - 'Modules/compute-vm/**'
      - 'Modules/cloud-sql/**'
      - 'Modules/storage-bucket/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yaml
    with:
      workload-path: Spoke/Clynz
      environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
      run-apply: ${{ github.event_name == 'push' }}
    secrets: inherit
