# ======================================================================
# Clynz Team Pipeline
# ======================================================================

name: Deploy Clynz

on:
  push:
    branches: [dev, staging, prod]
    paths:
      - 'Deployment/Spoke/Clynz/**'
      - 'Workload/Spoke/Clynz/**'
      - 'Modules/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yaml
    with:
      workload-path: Spoke/Clynz
      environment: ${{ github.ref_name }}
    secrets: inherit
