# ======================================================================
# Core Pipeline — manages team folders
# ======================================================================

name: Deploy Core

on:
  pull_request:
    branches: [dev, staging, prod]
    paths:
      - 'Deployment/Core/**'
      - 'Workload/Core/**'
  push:
    branches: [dev, staging, prod]
    paths:
      - 'Deployment/Core/**'
      - 'Workload/Core/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yaml
    with:
      workload-path: Core
      environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
      run-apply: ${{ github.event_name == 'push' }}
    secrets: inherit
